# -*- coding: utf-8 -*-
"""DS-Exp02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wAAmpuV2MJg0br5fl9TG1cGAriSsXB3U
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

dt = pd.read_csv("/content/titanic_dataset.csv")

dt

dt.info()

dt.describe()

print("Number of rows:",dt.shape[0])
print("Number of columns:",dt.shape[1])

dt

dt.set_index('PassengerId',inplace=True)
dt

categorical_cols = dt.select_dtypes(include=['object']).columns
for col in categorical_cols:
  print(f"\nValue counts for {col}:\n{dt[col].value_counts()}")

sns.countplot(x='Survived', data=dt)
plt.show()

print(dt['Pclass'].unique())
dt

dt.rename(columns= {'Sex':'Gender'}, inplace = True)
dt

sns.catplot(x= 'Survived', hue='Gender', kind='count', data=dt)

plt.show()

sns.boxplot(x= 'Survived', y='Age', data=dt)

plt.show()

sns.catplot(x='Survived', hue='Pclass', kind='count', data=dt)
plt.show()

corr_matrix=dt.select_dtypes(include=np.number).corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.show()

sns.pairplot(dt, hue="Survived")
plt.show()